# Generated by Django 6.0.7 on 2026-08-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_venta_detalleventa'),
        ('core', '0005_productoventahistorial'),
    ]

    operations = [
    ]
